// Seeds the database using the backend's own .env credentials.
// The DB password never leaves backend/.env â€” safe for shared projects.
// Usage: npm run seed   (after setting DB_PASSWORD in backend/.env)
import 'dotenv/config';
import pg from 'pg';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbDir = path.join(__dirname, '..', '..', 'database');

if (!process.env.DB_PASSWORD || process.env.DB_PASSWORD === 'PLACEHOLDER_NOT_SET') {
  console.error('ERROR: DB_PASSWORD is not set in backend/.env');
  console.error('Open backend/.env and set DB_PASSWORD to your Supabase database password.');
  process.exit(1);
}

const isPooler = String(process.env.DB_HOST || '').includes('pooler.supabase.com');

const pool = new pg.Pool({
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT || 5432),
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  ssl: process.env.DB_SSL === 'true' ? { rejectUnauthorized: false } : undefined,
  connectionTimeoutMillis: 15000,
});

const run = async () => {
  let client;
  try {
    client = await pool.connect();

    // Step 1 â€” apply pending migrations (idempotent: new tables,
    // widened image columns). Missing tables would break the seed below.
    const migDir = path.join(dbDir, 'migrations');
    if (fs.existsSync(migDir)) {
      for (const file of fs.readdirSync(migDir).filter((f) => f.endsWith('.sql')).sort()) {
        console.log(`Applying migration: ${file}`);
        const migSql = fs.readFileSync(path.join(migDir, file), 'utf8');
        await client.query(migSql);
      }
    }

    // Step 2 â€” ensure identity columns allow seed inserts (converts GENERATED
    // ALWAYS -> GENERATED BY DEFAULT; no-op if already correct)
    console.log('Step 2/3: preparing identity columns...');
    const fixSql = fs.readFileSync(path.join(dbDir, 'fix-identity.sql'), 'utf8');
    await client.query(fixSql);

    // Step 3 â€” run the full seed (truncates + inserts sample data)
    // Uses a dedicated connection with prepared statements disabled so it
    // works through the Supabase transaction pooler (port 6543).
    console.log('Step 3/3: seeding sample data...');
    const seedSql = fs.readFileSync(path.join(dbDir, 'seed.sql'), 'utf8');
    const statements = seedSql
      .split(/;\s*\r?\n/)
      .map((s) => s.replace(/--.*$/gm, '').trim())
      .filter((s) => s.length > 0 && !s.startsWith('SELECT setval'));
    for (const stmt of statements) {
      await client.query(stmt);
    }
    const setvalStmts = seedSql
      .split(/;\s*\r?\n/)
      .map((s) => s.trim())
      .filter((s) => s.startsWith('SELECT setval'));
    for (const stmt of setvalStmts) {
      await client.query(stmt);
    }

    const counts = {};
    for (const t of ['users', 'categories', 'products', 'product_images', 'addresses', 'orders', 'order_items', 'payments', 'shipments', 'reviews', 'coupons', 'feedback', 'custom_design_requests', 'testimonials', 'wishlist']) {
      const r = await client.query(`SELECT COUNT(*)::int AS n FROM ${t}`);
      counts[t] = r.rows[0].n;
    }

    console.log('\n=== SEED COMPLETE ===');
    console.table(counts);
    console.log('\nDemo accounts:');
    console.log('  Admin    - admin@furnishing.local / (password was rotated - not printed here)');
    console.log('  Customer â€” customer@furnishing.local / customer123');
  } catch (err) {
    if (String(err.message).includes('password authentication failed')) {
      console.error('ERROR: Password authentication failed â€” check DB_PASSWORD in backend/.env');
    } else if (String(err.code) === 'ENOTFOUND' || String(err.message).includes('timeout')) {
      console.error('ERROR: Could not reach the database â€” check DB_HOST / internet connection.');
    } else {
      console.error('SEED FAILED:', err.message);
    }
    process.exitCode = 1;
  } finally {
    if (client) client.release();
    await pool.end();
  }
};

run();
