-- ============================================================
-- MIGRATION: site content + testimonials (run after schema.sql)
-- Safe to re-run (idempotent).
-- ============================================================

-- Widen image columns so base64 data URIs (imported from Google
-- image links or uploaded directly) fit in the DB.
ALTER TABLE categories      ALTER COLUMN image      TYPE TEXT;
ALTER TABLE products       ALTER COLUMN main_image TYPE TEXT;
ALTER TABLE product_images ALTER COLUMN image_url  TYPE TEXT;

-- Key/value store for admin-editable storefront content
-- (hero headline, hero subline, hero image, quote text, etc.)
CREATE TABLE IF NOT EXISTS site_content (
  key         VARCHAR(100) PRIMARY KEY,
  value       TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_site_content_updated_at BEFORE UPDATE ON site_content
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Homepage testimonials shown in the "Word of Mouth" section.
-- Avatar images are stored as base64 data URIs in avatar_image.
CREATE TABLE IF NOT EXISTS testimonials (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(150) NOT NULL,
  role         VARCHAR(150),
  location     VARCHAR(150),
  rating       INTEGER NOT NULL DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
  quote        TEXT NOT NULL,
  avatar_image TEXT,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_testimonials_active ON testimonials(is_active, sort_order);

CREATE TRIGGER trg_testimonials_updated_at BEFORE UPDATE ON testimonials
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Default content so the storefront works before an admin customizes it
INSERT INTO site_content (key, value) VALUES
  ('hero_headline', 'Furniture that makes every space feel like home.'),
  ('hero_subline', 'Discover thoughtfully selected furniture and furnishing essentials designed for homes, workspaces, and the places where life happens.'),
  ('hero_image', NULL),
  ('quote_text', 'Every space has a story. Make yours worth living in.')
ON CONFLICT (key) DO NOTHING;
